[package]
name = "tokio-uds"
version = "0.1.7"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tokio-rs/tokio-uds"
homepage = "https://github.com/tokio-rs/tokio-uds"
documentation = "https://docs.rs/tokio-uds"
description = """
Unix Domain sockets for Tokio
"""
categories = ["asynchronous"]

[badges]
travis-ci = { repository = "tokio-rs/tokio-uds" }
appveyor = { repository = "alexcrichton/tokio-uds" }

[dependencies]
bytes = "0.4"
futures = "0.1.11"
iovec = "0.1"
libc = "0.2"
log = "0.4"
mio = "0.6.5"
mio-uds = "0.6.4"
tokio-core = "0.1"
tokio-io = "0.1"
